FROM debian:jessie

RUN apt-get update

RUN apt-get -y install vim-nox git

RUN git clone git://github.com/Shougo/neobundle.vim.git $HOME/.vim/bundle/neobundle.vim
COPY home/.vimrc /root/.vimrc
RUN $HOME/.vim/bundle/neobundle.vim/bin/neoinstall

COPY home/.gitconfig /root/.gitconfig

WORKDIR /home/workspace
ENTRYPOINT ["vim"]
